// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9rvZ0QvSKeyDULvWgWqr0dQedOPewEI8',
    appId: '1:983695819853:web:2284de091ec2ed844b0804',
    messagingSenderId: '983695819853',
    projectId: 'tokio-test-campos',
    authDomain: 'tokio-test-campos.firebaseapp.com',
    storageBucket: 'tokio-test-campos.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7j6IHe9C9lZ8zPLvh0alrQ18MbsVAfaQ',
    appId: '1:983695819853:android:734cc9a1fe8bf5e24b0804',
    messagingSenderId: '983695819853',
    projectId: 'tokio-test-campos',
    storageBucket: 'tokio-test-campos.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_0bM_BNimCgs9EvGoCBpPpKW_A_Hwcr8',
    appId: '1:983695819853:ios:b840a1dbfb4bd18c4b0804',
    messagingSenderId: '983695819853',
    projectId: 'tokio-test-campos',
    storageBucket: 'tokio-test-campos.firebasestorage.app',
    iosBundleId: 'com.tokio.app',
  );
}
